---
name: Zotero to Readwise Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "9 4 * * *"

permissions:
  contents: read

jobs:
  zotero-to-readwise-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.11
      - run: uv run python3 zotero2readwise/run.py --include_annotations yes --include_notes yes ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}
